### ISSUE TITLE
KeyError: "The following positions are missing from the montage definitions:

### ISSUE THREAD

**Issue by tarekul** [edrias/seniorprojecteeg#20]
I am not able to solve this problem. Need help. 
![screen shot 2018-09-18 at 1 39 33 am](https://user-images.githubusercontent.com/8740743/45865588-ff67f500-bd4b-11e8-8d44-40f0f3271ea1.png)

`path = '/Volumes/flashDrive/EEGLAB/SA20140304/20140304_1418.set'`
`mne.io.read_raw_eeglab(path)`

**Comment by edrias** [comment]
Which version of MNE are you using?

**Comment by tarekul** [comment]
In Anaconda environment search I can't find MNE in python 3.6. In 2.7 anaconda I was able to find it and install it in the environment. Do you know of any workaround here?
